spring: 
  session:
    store-type: redis
    # user-defined
    redis:
      namespace: "htdp1:session"
      host: 127.0.0.1
      port: 7000
      password: 

  cache: 
    type: redis
    # user-defined
    redis:
      namespace: "htdp1:dept-spring:cache:"
      ttl: 10 # min
      host: 127.0.0.1
      port: 16379
      password:
      
  # user-defined
  repository: 
    type: redis
    redis:
      namespace: ""
      host: 127.0.0.1
      port: 16379
      password:
