server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    cache:
      instrument: true
      
spring:
  config:
    import: 
    - application-apis.yml
    - application-mariadb.yml
    - application-redis.yml
  application:
    name: dept-spring
  data:
    rest:
      basePath: /api

logging:
  level:
    '[com.htdp1.deptspring]': debug