server:
  port: 8080
  servlet:
    context-path: /dept-spring 

management:
  endpoints:
    web:
      exposure:
        include: "*"
      
spring:
  config:
    import: 
    - application-apis.yml
    - application-mariadb.yml
    - application-redis.yml
  application:
    name: dept-spring
  data:
    rest:
      basePath: /api

logging:
  level:
    '[com.htdp1.deptspring]': debug

### user defined ###
session:
  enabled: false

